/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Management API
 * API for managing hospital ambulances, procedures, and payments.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xkokavecs@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetAmbulanceSummary200Response
 */
export interface GetAmbulanceSummary200Response {
    /**
     *
     * @type {number}
     * @memberof GetAmbulanceSummary200Response
     */
    totalCost?: number;
}

/**
 * Check if a given object implements the GetAmbulanceSummary200Response interface.
 */
// @ts-ignore
export function instanceOfGetAmbulanceSummary200Response(value: object): value is GetAmbulanceSummary200Response {
    return true;
}

export function GetAmbulanceSummary200ResponseFromJSON(json: any): GetAmbulanceSummary200Response {
    return GetAmbulanceSummary200ResponseFromJSONTyped(json, false);
}

// @ts-ignore
export function GetAmbulanceSummary200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAmbulanceSummary200Response {
    if (json == null) {
        return json;
    }
    return {

        'totalCost': json['totalCost'] == null ? undefined : json['totalCost'],
    };
}

export function GetAmbulanceSummary200ResponseToJSON(json: any): GetAmbulanceSummary200Response {
    return GetAmbulanceSummary200ResponseToJSONTyped(json, false);
}

// @ts-ignore
export function GetAmbulanceSummary200ResponseToJSONTyped(value?: GetAmbulanceSummary200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'totalCost': value['totalCost'],
    };
}

