/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AmbulanceListComponent {
    }
    interface AppComponent {
    }
}
declare global {
    interface HTMLAmbulanceListComponentElement extends Components.AmbulanceListComponent, HTMLStencilElement {
    }
    var HTMLAmbulanceListComponentElement: {
        prototype: HTMLAmbulanceListComponentElement;
        new (): HTMLAmbulanceListComponentElement;
    };
    interface HTMLAppComponentElement extends Components.AppComponent, HTMLStencilElement {
    }
    var HTMLAppComponentElement: {
        prototype: HTMLAppComponentElement;
        new (): HTMLAppComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ambulance-list-component": HTMLAmbulanceListComponentElement;
        "app-component": HTMLAppComponentElement;
    }
}
declare namespace LocalJSX {
    interface AmbulanceListComponent {
    }
    interface AppComponent {
    }
    interface IntrinsicElements {
        "ambulance-list-component": AmbulanceListComponent;
        "app-component": AppComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ambulance-list-component": LocalJSX.AmbulanceListComponent & JSXBase.HTMLAttributes<HTMLAmbulanceListComponentElement>;
            "app-component": LocalJSX.AppComponent & JSXBase.HTMLAttributes<HTMLAppComponentElement>;
        }
    }
}
